# Generated by Django 4.2.4 on 2023-08-10 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_xid', models.CharField(max_length=255, unique=True)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('enabled', 'enabled'), ('disabled', 'disabled')], default='disabled', max_length=50)),
                ('enabled_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='deposit', max_length=50)),
                ('reference_id', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/time this object was created.', verbose_name='created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.walletmodel')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
